name: Build and deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y make gettext curl unzip

    - name: Install node packages
      run: npm ci

    - name: Build site
      run: make

    - name: Upload site
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

    - name: Deploy site
      uses: actions/deploy-pages@v4
